### ISSUE TITLE
Syncing Error, Exception Unhandled

### ISSUE THREAD

**Issue by igorgue** [hodlwallet/liviano#4]
```cs
[Sync] There was an error during sync: One or more errors occurred. (Collection was modified; enumeration operation may not execute.)
[Sync] Stacktrace: '   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, CancellationToken cancellationToken)
   at Liviano.Electrum.TrustedServer.<>c__DisplayClass67_0.<SyncAccount>b__0(Object o) in /home/igor/Code/hodlwallet/liviano/Liviano/Electrum/TrustedServer.cs:line 511
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Liviano.Electrum.TrustedServer.SyncAccount(IAccount acc, CancellationToken ct) in /home/igor/Code/hodlwallet/liviano/Liviano/Electrum/TrustedServer.cs:line 510
   at Liviano.Wallet.ElectrumPool_OnConnectedToSync(Object sender, Server server, CancellationToken ct) in /home/igor/Code/hodlwallet/liviano/Liviano/Wallet.cs:line 463
   at Liviano.Wallet.SyncTask() in /home/igor/Code/hodlwallet/liviano/Liviano/Wallet.cs:line 440
   at Liviano.Wallet.Sync() in /home/igor/Code/hodlwallet/liviano/Liviano/Wallet.cs:line 335'
```

Fix a problem in syncing that happens sometimes.

**Comment by igorgue** [comment]
I haven't seen this in ages... I think I fix it on many of my async strategies rewrites
